# Generated by Django 2.2 on 2021-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(related_name='orders', to='poorly_coded_store.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quanitity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
