# Generated by Django 2.2 on 2021-03-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_auto_20210329_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
